#!/bin/bash

# sacred git
sudo apt install git
# installing emacs
sudo apt install emacs
# installing ripgrep (idk wats this but doom needs it)
sudo apt install ripgrep
# install fd (idk wats this either but seems like doom works better with it)
sudo apt install fd-find

# install doom emacs
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
